### Get details
GET {{URL}}/conference

###Change details
POST {{URL}}/conference
Content-Type: application/json

{
  "name": "Name of the conference",
  "startDate": "15.04.2020",
  "endDate": "15.04.2020",
  "submissionDeadline": "15.04.2020",
  "proposalDeadline": "15.04.2020",
  "biddingDeadline": "15.04.2020",
  "submitPaperEarly": false,
  "currentPhase": 0
}

##### User management
### List users
GET {{URL}}/users

### Update type and validation
PUT {{URL}}/users
Content-Type: application/json

{
  "userId": 1,
  "type": 1,
  "validated": true
}