### Get all papers
GET {{URL}}/paper/assign

### Check bid result of PC member
POST {{URL}}/paper/assign
Content-Type: application/json

{
  "paperId": 6,
  "userId": 10
}

### Get all PC members
GET {{URL}}/member

### Assign paper to PC member
PUT {{URL}}/paper/assign
Content-Type: application/json

{
  "userId": 10,
  "paperId": 6
}