##### Authentication
### Login
POST {{URL}}/authentication/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Logout
POST {{URL}}/authentication/logout

### Get user information
GET {{URL}}/authentication


##### Conference
### Get details
GET {{URL}}/conference

###Change details
POST {{URL}}/conference
Content-Type: application/json

{
  "name": "Name of the conference",
  "startDate": "15.04.2020",
  "endDate": "15.04.2020",
  "abstractDeadline": "15.04.2020",
  "proposalDeadline": "15.04.2020",
  "biddingDeadline": "15.04.2020",
  "submitPaperEarly": false
}

### Get phase (0, 1, 2, 3)
GET {{URL}}/conference/phase


##### Papers
### Get list of papers
GET {{URL}}/papers

### Submit proposal
POST {{URL}}/papers
Content-Type: application/json

{
  "field": "text",
  "proposalName": "text",
  "keywords": "text",
  "topics": "text",
  "listOfAuthors": "text"
}

### Upload full paper
PUT {{URL}}/papers
Content-Type: multipart/form-data